[package]
name = "linear_regression"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lr_classic"
path = "src/bin/lr_classic.rs"

[[bin]]
name = "lr_with_gradient" 
path = "src/bin/lr_with_gradient.rs"

[dependencies]