[package]
name = "linear_regression"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lr_classic"
path = "src/lr_classic/mod.rs"

[[bin]]
name = "lr_with_gradient"
path = "src/lr_with_gradient/mod.rs"

[dependencies]
shared_functions = { path = "../shared_functions" }
